query GetAllNews($page: Int, $limit: Int) {
  news(page: $page, limit: $limit, sort: ["-date_created"]) {
    ...NewsFragment
  }
  news_aggregated {
    count {
      id
    }
  }
}

query GetNewsByRegion($regionCode: String!) {
  news(filter: { region: { code: { _eq: $regionCode } } }, limit: 6) {
    id
    title
    date_created
  }
}

query GetNewsById($id: ID!) {
  news_by_id(id: $id) {
    ...NewsFragment
    content
    images {
      directus_files_id {
        type
        title
        id
      }
    }
  }
}
