query GetAllNews {
  news {
    ...NewsFragment
  }
}

query GetNewsByRegion($regionCode: String!) {
  news(filter: { region: { code: { _eq: $regionCode } } }, limit: 6) {
    id
    title
    date_created
  }
}
