query GetAllRepresentatives {
  representatives {
    ...RepresentativesFragment
  }
}

query GetRepresentativesByRegion($regionCode: String!) {
  representatives(filter: { region: { code: { _eq: $regionCode } } }) {
    ...RepresentativesFragment
  }
}
