import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { lato, trola } from "@/shared/assets/fonts";
import { Footer } from "@/components/footer";
import { Providers } from "@/shared/providers/providers";

import "@/shared/assets/css/globals.css";
import "@/shared/assets/css/typography.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Палата молодых законодателей при СФ РФ",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={`${montserrat.variable} ${lato.variable} ${trola.variable} h-full antialiased`}
    >
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                const theme = JSON.parse(localStorage.getItem('theme') || '{}');
                if (theme.state?.isDark) {
                  document.documentElement.classList.add('dark');
                }
              } catch {}
            `,
          }}
        />
      </head>

      <body className="flex min-h-full flex-col">
        <Providers>
          {children}

          <Footer />
        </Providers>
      </body>
    </html>
  );
}
