import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { lato, trola } from "@/shared/assets/fonts";
import "@/shared/assets/css/globals.css";
import "@/shared/assets/css/typography.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { Providers } from "@/shared/providers/providers";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["700", "800"],
});

export const metadata: Metadata = {
  title: "Палата молодых законодателей при СФ РФ",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${montserrat.variable} ${lato.variable} ${trola.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <Providers>
          <Header />

          <main className="grow">{children}</main>

          <Footer />
        </Providers>
      </body>
    </html>
  );
}
