query GetChamberMembersPage($page: Int, $limit: Int) {
  users(
    filter: { status: { _eq: "active" }, member: { _eq: true } }
    sort: ["last_name", "first_name"]
    page: $page
    limit: $limit
  ) {
    ...UserFragment
  }

  users_aggregated(
    filter: { status: { _eq: "active" }, member: { _eq: true } }
  ) {
    count {
      id
    }
  }
}
