query GetHomePage {
  home_page {
    popular_news {
      id
      news_id {
        ...NewsFragment
      }
    }

    chamber_chairman {
      first_name
      last_name
      email
      avatar {
        ...MediaFragment
      }
    }

    chairman_featured_news {
      id
      title
      preview {
        ...MediaFragment
      }
      date_created
    }

    chairman_video {
      ...MediaFragment
    }
  }
}
