export const regions = [
  { code: "RU-MOW", title: "Москва" },
  { code: "RU-SPE", title: "Санкт-Петербург" },
  { code: "RU-MOS", title: "Московская область" },
  { code: "RU-KR", title: "Республика Карелия" },
  { code: "RU-KO", title: "Республика Коми" },
  { code: "RU-ARK", title: "Архангельская область" },
  { code: "RU-NEN", title: "Ненецкий АО" },
  { code: "RU-MUR", title: "Мурманская область" },
  { code: "RU-LEN", title: "Ленинградская область" },
  { code: "RU-NGR", title: "Новгородская область" },
  { code: "RU-PSK", title: "Псковская область" },
  { code: "RU-TVE", title: "Тверская область" },
  { code: "RU-SMO", title: "Смоленская область" },
  { code: "RU-YAR", title: "Ярославская область" },
  { code: "RU-KOS", title: "Костромская область" },
  { code: "RU-IVA", title: "Ивановская область" },
  { code: "RU-VLG", title: "Вологодская область" },
  { code: "RU-VLA", title: "Владимирская область" },
  { code: "RU-KLU", title: "Калужская область" },
  { code: "RU-TUL", title: "Тульская область" },
  { code: "RU-RYA", title: "Рязанская область" },
  { code: "RU-BRY", title: "Брянская область" },
  { code: "RU-ORL", title: "Орловская область" },
  { code: "RU-KRS", title: "Курская область" },
  { code: "RU-BEL", title: "Белгородская область" },
  { code: "RU-LIP", title: "Липецкая область" },
  { code: "RU-VOR", title: "Воронежская область" },
  { code: "RU-TAM", title: "Тамбовская область" },
  { code: "RU-PNZ", title: "Пензенская область" },
  { code: "RU-NIZ", title: "Нижегородская область" },
  { code: "RU-MO", title: "Республика Мордовия" },
  { code: "RU-CU", title: "Чувашская Республика" },
  { code: "RU-ME", title: "Республика Марий Эл" },
  { code: "RU-TA", title: "Республика Татарстан" },
  { code: "RU-UD", title: "Удмуртская Республика" },
  { code: "RU-KIR", title: "Кировская область" },
  { code: "RU-SAM", title: "Самарская область" },
  { code: "RU-ULY", title: "Ульяновская область" },
  { code: "RU-SAR", title: "Саратовская область" },
  { code: "RU-VGG", title: "Волгоградская область" },
  { code: "RU-ROS", title: "Ростовская область" },
  { code: "RU-AST", title: "Астраханская область" },
  { code: "RU-KL", title: "Республика Калмыкия" },
  { code: "RU-AD", title: "Республика Адыгея" },
  { code: "RU-KDA", title: "Краснодарский край" },
  { code: "RU-STA", title: "Ставропольский край" },
  { code: "RU-DA", title: "Республика Дагестан" },
  { code: "RU-CE", title: "Чеченская Республика" },
  { code: "RU-IN", title: "Республика Ингушетия" },
  { code: "RU-SE", title: "Республика Северная Осетия — Алания" },
  { code: "RU-KB", title: "Кабардино-Балкарская Республика" },
  { code: "RU-KC", title: "Карачаево-Черкесская Республика" },
  { code: "RU-BA", title: "Республика Башкортостан" },
  { code: "RU-ORE", title: "Оренбургская область" },
  { code: "RU-CHE", title: "Челябинская область" },
  { code: "RU-KGN", title: "Курганская область" },
  { code: "RU-TYU", title: "Тюменская область" },
  { code: "RU-KHM", title: "Ханты-Мансийский АО - Югра" },
  { code: "RU-YAN", title: "Ямало-Ненецкий АО" },
  { code: "RU-SVE", title: "Свердловская область" },
  { code: "RU-PER", title: "Пермский край" },
  { code: "RU-TOM", title: "Томская область" },
  { code: "RU-NVS", title: "Новосибирская область" },
  { code: "RU-OMS", title: "Омская область" },
  { code: "RU-KEM", title: "Кемеровская область" },
  { code: "RU-ALT", title: "Алтайский край" },
  { code: "RU-AL", title: "Республика Алтай" },
  { code: "RU-KK", title: "Республика Хакасия" },
  { code: "RU-TY", title: "Республика Тыва" },
  { code: "RU-KYA", title: "Красноярский край" },
  { code: "RU-IRK", title: "Иркутская область" },
  { code: "RU-BU", title: "Республика Бурятия" },
  { code: "RU-ZAB", title: "Забайкальский край" },
  { code: "RU-SA", title: "Республика Саха (Якутия)" },
  { code: "RU-AMU", title: "Амурская область" },
  { code: "RU-KHA", title: "Хабаровский край" },
  { code: "RU-YEV", title: "Еврейская автономная область" },
  { code: "RU-PRI", title: "Приморский край" },
  { code: "RU-SAK", title: "Сахалинская область" },
  { code: "RU-MAG", title: "Магаданская область" },
  { code: "RU-KAM", title: "Камчатский край" },
  { code: "RU-CHU", title: "Чукотский АО" },
  { code: "RU-KGD", title: "Калининградская область" },
  { code: "RU-CR", title: "Республика Крым" },
  { code: "RU-SEV", title: "Севастополь" },
  { code: "RU-HR", title: "Херсонская область" },
  { code: "RU-ZP", title: "Запорожская область" },
  { code: "RU-DON", title: "Донецкая Народная Республика" },
  { code: "RU-LUG", title: "Луганская Народная Республика" },
].sort((a, b) => a.title.localeCompare(b.title, "ru"));
